services:
  mindcraft:
    build: .
    environment:
      SETTINGS_JSON: |
        {"auto_open_ui": false}
    volumes:
      - ./settings.js:/app/settings.js
      - ./keys.json:/app/keys.json
      - ./profiles:/app/profiles
      - ./bots:/app/bots
    network_mode: "host"

  # viaproxy: #use this service to connect to an unsupported minecraft server versions. more info: ./services/viaproxy/README.md
  #   image: ghcr.io/viaversion/viaproxy:latest
  #   volumes:
  #     - ./services/viaproxy:/app/run
  #   ports:
  #     - "25568:25568"
  #   profiles:
  #     - viaproxy
  #   stdin_open: true
  #   tty: true
